#ifndef __CONFIG_h__
#define __CONFIG_h__

#define NAME_MAXLENGTH (10)
#define START_QUANTITY (4)
#define NUMBER_OF_PRODUCTS 6
#define DEFAULT_WANTED_TEMPERATURE (20)
#define DEFAULT_LIGHT_INTENSITY (70)
#define TEMPERATURE_OFFSET_TOLERANCE (20)
#define CURRENT_FREQ (50)
#define TURN_ON_AC_PERCENTAGE_LIMIT (10)

#endif
